version: '3'

services:
  php-app:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root   
      MYSQL_DATABASE: idordu              
      MYSQL_USER: du2024                  
      MYSQL_PASSWORD: du2024              
    volumes:
      - ./app/idordu.sql:/docker-entrypoint-initdb.d/idordu.sql  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
